### ISSUE TITLE
When running by hand after compiling by hand program crashes with FNFE

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [precol/MagicNumbers#3]
```
[tammo@lafk-T470 java]$ java Main                                                                           [INSERT]
txt
Exception in thread "main" java.io.FileNotFoundException: src\main\resources\Important.csv (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at Methods.reader(Methods.java:20)
	at Methods.compareBytes(Methods.java:53)
	at Main.main(Main.java:6)
```

You will either have to fix the Maven issue #1 and then have Maven-created JAR packed with files you wish to use or you will have to make the program accept files from outside via arguments.

To be honest, a program that checks only hard-coded files ain't impressive and to redo the code each time prior to using is a frowned-upon approach.

**Comment by precol** [comment]
I updated repository. I think I got rid of the problems. When it comes to
2nd mail, I think it was because I wrote ArrayList Instead of
ArrayList<String[]>. I encountered earlier "version 5 not supported" error
and had to change version of byte code and language level and it worked
however after downloading project from github and opening it it was set
back to earlier versions. I hope now this problem is also fixed.
Thank you for your tips.

Mikołaj Pecold

pt., 6 mar 2020 o 11:55 Tomasz Borek <notifications@github.com> napisał(a):

**Comment by LIttleAncientForestKami** [comment]
GitHub sent you mails about my comments on your repo, in form of an issue. So, I opened 3 issues in total, hence 3 emails. 

> I updated repository. 

Update is nice and you have my thanks for it. I'll split your answer and address it in relevant issues.

Dla pewności, że wszystko jest jasne, przejdę też na polski. Problemem tutaj jest fakt, że Twój program działa tylko dla podanego mu na sztywno pliku: `iggy.jpg`. Jak nie odpalam go z IDE to nie działa (dowód? ściągnąłem nową wersję i komunikat wiele się nie zmienił: log poniżej).

Oznacza to, że jeśli nie zaingeruję w kod, nie sprawdzi mi innego pliku niż ten wszyty weń. Jak mam np. swój własny plik do sprawdzenia... to muszę być programistą by użyć Twojego programu. 

W specce jest "showcase your skills": czy to już mamy w kodzie?

Log:

```
[tammo@lafk-T470 classes]$ ls                                                                               [INSERT]
iggy.jpg  Important.csv  Main.class  META-INF  Methods.class  Zeszyt1.csv
[tammo@lafk-T470 classes]$ java Main                                                                        [INSERT]
jpg
Exception in thread "main" java.io.FileNotFoundException: src\main\resources\Important.csv (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at Methods.reader(Methods.java:20)
	at Methods.compareBytes(Methods.java:53)
	at Main.main(Main.java:6)
```

**Comment by LIttleAncientForestKami** [comment]
Z innego wątku, odpowiadam tutaj, bo dotyczy tej sprawy:

> using unchecked operations and didn't have a FNFE. If program still isn't working properly I can work on it more, however at the moment I can't say what exactly causes problems.

Spójrz proszę na ten komunikat błędu (sklonowałem repozytorium od zera i odpaliłem przed momentem i dostałem ten sam jak powyżej).

> Exception in thread "main" java.io.FileNotFoundException: src\main\resources\Important.csv (Nie ma takiego pliku ani katalogu)

**Moje pytanie: dlaczego Twój program szuka takiego pliku?**

Maven buduje wszystko ładnie. Spakowany przezeń JAR nie wie jak się ma odpalać, bo nie ma informacji co jest główną klasą. Konfiguracja Mavena w tym względzie jest wybrakowana, zatem paczka jest budowana bez informacji jak ją odpalić. Zatem `java -jar target/tuNazwaPliku.jar` nie działa.

Można te klasy skompilowane odpalić, ponieważ Maven umieszcza skompilowane klasy w katalogu `target/classes`. Po takim odpaleniu 'z ręki' dostaje się komunikat powyżej. 

Moje drugie pytanie, zadane wcześniej już: **W specce jest "showcase your skills": czy to już mamy w kodzie?**

**Comment by precol** [comment]
I updated the repository. I hope FNFE is solved. I thought about how I could showcase my skills in other ways, but I am too inexperienced yet in order to think exactly what elements I can improve and in what way, however if you could tell me what I should work on I would apreciate it very much.
